In [1]:
import numpy as np

In [2]:
# lineer cebir kütüphanesi

## numpy array

In [3]:
benimListem = [20,30,40]

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixList = [[10,20,30],[30,40,50],[7,10,85]]

In [6]:
np.array(matrixList)

array([[10, 20, 30],
       [30, 40, 50],
       [ 7, 10, 85]])

## arange

In [8]:
np.arange(0,10) #belirli aralıkta array oluşturmak için

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2) #step size 2 

array([0, 2, 4, 6, 8])

## zeros

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [19]:
np.linspace(0,20,30) #eşit boşluklarla array oluşturma

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

## eye

In [20]:
#identity matrix

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [24]:
np.random.randn(8) #tek boyutlu 8 elemanlı random bir array döndürür

array([ 0.85624494,  0.61488279, -1.24420889, -1.04487294,  0.81163312,
       -1.95418794, -0.00962957,  0.26114311])

In [25]:
np.random.randint(1,10,5) # 1 den 10a kadar random 5 tane int rakamdan oluşan array döndürür

array([5, 8, 2, 3, 2])

In [26]:
randomDizi = np.random.randint(0,100,20)

In [27]:
randomDizi

array([44, 79, 41,  5, 43, 70, 56, 85,  9,  9, 44, 15, 12, 17, 99, 43, 71,
       93, 10, 43])

## numpy dizi metotları

In [31]:
benimNumpyDizim = np.arange(30)

In [32]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
benimNumpyDizim.max()

29

In [36]:
randomDizi.max()

99

In [37]:
randomDizi.argmax()

14

In [40]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [42]:
reshapeDizim.shape

(5, 6)