In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [5]:
benimDizim[3:8] = -5

In [6]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [7]:
baskaDizi = np.arange(0,24)

In [8]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingDizisi = baskaDizi[4:9]

In [14]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [15]:
slicingDizisi[:]=700

In [16]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [17]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
ornekDizi = np.arange(0,24)

In [19]:
ornekDiziKopya = ornekDizi.copy()

In [20]:
ornekDiziKopyaSlicing = ornekDiziKopya[3:6]

In [21]:
ornekDiziKopyaSlicing[:]=600

In [22]:
ornekDiziKopyaSlicing

array([600, 600, 600])

In [23]:
ornekDizi ## asıl dizide değerler değişmedi, kopyasıyla çalışmak gerekir

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [24]:
benimListe = [[10,20,30],[20,30,40],[40,50,60]]

In [26]:
matrix = np.array(benimListe)

In [27]:
matrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [28]:
matrix[0][2]

30

In [33]:
matrix[:,:1]

array([[10],
       [20],
       [40]])

In [35]:
yeniListe = [[10,20,30],[20,30,40],[40,50,60],[10,11,12],[13,14,15]]

In [36]:
yeniMatriks = np.array(yeniListe)

In [38]:
yeniMatriks

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60],
       [10, 11, 12],
       [13, 14, 15]])

In [37]:
yeniMatriks[[0,2,4]]

array([[10, 20, 30],
       [40, 50, 60],
       [13, 14, 15]])

 ## operasyonlar

In [39]:
yeniDizi = np.arange(5,25)

In [40]:
yeniDizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [41]:
yeniDizi = np.random.randint(10,100,20)

In [42]:
yeniDizi

array([70, 77, 95, 73, 84, 16, 60, 90, 63, 79, 50, 14, 11, 98, 36, 47, 49,
       32, 10, 84])

In [44]:
yeniDizi[yeniDizi>30]

array([70, 77, 95, 73, 84, 60, 90, 63, 79, 50, 98, 36, 47, 49, 32, 84])